# Generated by Django 5.2.1 on 2025-06-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ManyToManyField(related_name='courses_related_types', to='course.coursetype', verbose_name='Kursning darajalari'),
        ),
    ]
