# Generated by Django 5.2.1 on 2025-06-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
