# Generated by Django 5.2.1 on 2025-06-03 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('transaction', '0002_transaction_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_course', to='course.course'),
        ),
    ]
