# Generated by Django 5.2.1 on 2025-07-08 18:02

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idioms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Idioms',
                'verbose_name_plural': 'Idioms',
            },
        ),
    ]
