# Generated by Django 5.2.1 on 2025-07-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='chat_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
