# Generated by Django 5.2.1 on 2025-07-08 18:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_course_type_course_course_type'),
        ('theme', '0001_initial'),
        ('upload', '0002_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='course_type',
            field=models.ManyToManyField(related_name='courses_related_themes', to='course.coursetype', verbose_name='Kursning darajalari'),
        ),
        migrations.AddField(
            model_name='theme',
            name='schreiben',
            field=models.TextField(blank=True, null=True, verbose_name='Schreiben mavzusi'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sprechen',
            field=models.TextField(blank=True, null=True, verbose_name='Sprechen mavzusi'),
        ),
        migrations.AddField(
            model_name='theme',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='theme',
            name='course',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='video',
        ),
        migrations.CreateModel(
            name='ThemeAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_attendance', models.BooleanField(default=True)),
                ('is_complete_test', models.BooleanField(default=False)),
                ('ball', models.IntegerField(default=0)),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes_attendance_themes', to='theme.theme')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThemeExamples',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('course', models.ManyToManyField(related_name='themes_example_course', to='course.course')),
                ('video', models.ManyToManyField(related_name='themes_examle_video', to='upload.video')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='theme',
            name='course',
            field=models.ManyToManyField(related_name='themes_course', to='course.course'),
        ),
        migrations.AddField(
            model_name='theme',
            name='materials',
            field=models.ManyToManyField(related_name='themes_materials', to='upload.file'),
        ),
        migrations.AddField(
            model_name='theme',
            name='video',
            field=models.ManyToManyField(related_name='themes_video', to='upload.video'),
        ),
    ]
