# Generated by Django 5.2.1 on 2025-06-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_alter_themeattendance_is_attendance'),
        ('upload', '0002_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='video',
        ),
        migrations.AddField(
            model_name='theme',
            name='video',
            field=models.ManyToManyField(related_name='themes_video', to='upload.video'),
        ),
    ]
