# Generated by Django 5.2.1 on 2025-06-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_course_type_course_course_type'),
        ('theme', '0003_remove_theme_video_theme_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='course_type',
            field=models.ManyToManyField(related_name='courses_related_themes', to='course.coursetype', verbose_name='Kursning darajalari'),
        ),
    ]
