# Generated by Django 5.2.1 on 2025-06-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_theme_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='schreiben',
            field=models.TextField(blank=True, null=True, verbose_name='Schreiben mavzusi'),
        ),
        migrations.AddField(
            model_name='theme',
            name='sprechen',
            field=models.TextField(blank=True, null=True, verbose_name='Sprechen mavzusi'),
        ),
        migrations.AddField(
            model_name='theme',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
