# Generated by Django 5.2.1 on 2025-07-03 04:28

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_course_type_course_course_type'),
        ('theme', '0005_theme_schreiben_theme_sprechen_theme_youtube'),
        ('upload', '0002_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='course',
        ),
        migrations.CreateModel(
            name='ThemeExamples',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('course', models.ManyToManyField(related_name='themes_example_course', to='course.course')),
                ('video', models.ManyToManyField(related_name='themes_examle_video', to='upload.video')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='theme',
            name='course',
            field=models.ManyToManyField(related_name='themes_course', to='course.course'),
        ),
    ]
