# Generated by Django 5.2.1 on 2025-07-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0006_remove_theme_course_themeexamples_theme_course'),
        ('upload', '0002_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='materials',
        ),
        migrations.AddField(
            model_name='theme',
            name='materials',
            field=models.ManyToManyField(related_name='themes_materials', to='upload.file'),
        ),
    ]
